stepback: false

# FUNCTIONS
functions:
  "fetchSource" :
    - command: git.get_project
      params:
        directory: "src"
  "buildDebianLinuxToolchain":
    command: shell.exec
    params:
      working_dir: "src"
      script: |
        set -o errexit
        set -o xtrace
        ./build-debian-linux-toolchain.sh ${arch}
  "buildRHELLinuxToolchain":
    command: shell.exec
    params:
      working_dir: "src"
      script: |
        set -o errexit
        set -o xtrace
        ./build-rhel-linux-toolchain.sh
  "uploadToolchain":
    command: s3.put
    params:
      aws_key: ${aws_key}
      aws_secret: ${aws_secret}
      local_file: src/php.tar.gz
      remote_file: ${aws_prefix}/${build_variant}/${revision}/${build_id}.tar.gz
      bucket: mciuploads
      permissions: public-read
      content_type: ${content_type|application/x-gzip}
  "pushToolchainRelease":
    command: s3Copy.copy
    params:
      aws_key: ${aws_key}
      aws_secret: ${aws_secret}
      s3_copy_files:
        - { 'source': { 'path': '${aws_prefix}/${build_variant}/${revision}/${build_id}.tar.gz', 'bucket': 'mciuploads' },
            'destination': { 'path': 'build/toolchain-drivers/mongo-php-driver/php-toolchain-${build_variant}-${revision}.tar.gz', 'bucket': 'boxes.10gen.com' }
          }

# PRE/POST TASKS
pre:
  - func: fetchSource

# TASK DEFINITIONS
tasks:
  - name: build-debian-linux-toolchain
    commands:
      - func: buildDebianLinuxToolchain
      - func: uploadToolchain

  - name: push-debian-linux-binaries
    depends_on:
    - name: build-debian-linux-toolchain
    stepback: false
    commands:
      - func: pushToolchainRelease

  - name: build-rhel-linux-toolchain
    commands:
      - func: buildRHELLinuxToolchain
      - func: uploadToolchain

  - name: push-rhel-linux-binaries
    depends_on:
    - name: build-rhel-linux-toolchain
    stepback: false
    commands:
      - func: pushToolchainRelease

# BUILD VARIANTS

buildvariants:

## OpenSSL 1.1.0
- name: debian92-64bit
  display_name: Debian 9.2 64-bit
  run_on:
    - debian92-build
  tasks:
     - name: build-debian-linux-toolchain
     - name: push-debian-linux-binaries

## OpenSSL 1.0.2
- name: ubuntu1604-64bit
  display_name: Ubuntu 16.04 64-bit
  run_on:
    - ubuntu1604-build
  tasks:
     - name: build-debian-linux-toolchain
     - name: push-debian-linux-binaries

- name: rhel70-64bit
  display_name: RHEL 7.0 64-bit
  run_on:
    - rhel70
  tasks:
     - name: build-rhel-linux-toolchain
     - name: push-rhel-linux-binaries

- name: rhel71-power8
  display_name: RHEL 7.1 Power 8
  run_on:
    - rhel71-power8-build
  tasks:
     - name: build-rhel-linux-toolchain
     - name: push-rhel-linux-binaries

- name: rhel72-zseries
  display_name: RHEL 7.2 zSeries
  run_on:
    - rhel72-zseries-build
  tasks:
     - name: build-rhel-linux-toolchain
     - name: push-rhel-linux-binaries

- name: ubuntu1604-arm64
  display_name: Ubuntu 16.04 ARM64
  run_on:
    - ubuntu1604-arm64-small
  tasks:
     - name: build-debian-linux-toolchain
     - name: push-debian-linux-binaries

- name: ubuntu1804-amd64
  display_name: Ubuntu 18.04 AMD64
  run_on:
    - ubuntu1804-small
  tasks:
     - name: build-debian-linux-toolchain
     - name: push-debian-linux-binaries

- name: ubuntu1804-arm64
  display_name: Ubuntu 18.04 ARM64
  run_on:
    - ubuntu1804-arm64-test
  tasks:
     - name: build-debian-linux-toolchain
     - name: push-debian-linux-binaries
